/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BinaryTreeMain */

#ifndef _Included_BinaryTreeMain
#define _Included_BinaryTreeMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BinaryTreeMain
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_BinaryTreeMain_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
